#!/bin/bash

USER_NAME=
MAIL_ADDR=
GIT_PARAM="
GIT_AUTHOR_NAME=$USER_NAME; 
GIT_AUTHOR_EMAIL='$MAIL_ADDR'; 
GIT_COMMITTER_NAME=$USER_NAME; 
GIT_COMMITTER_EMAIL='$MAIL_ADDR'; 
"
git filter-branch -f \
  --env-filter "$GIT_PARAM" HEAD
